[project]
name = "iris-mnemosia-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "GOMES Mathéo",email = "matheo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)",
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "alembic (>=1.20.0,<2.0.0)"
]

[tool.poetry]
packages = [{include = "iris_mnemosia_backend", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
